import type { Metadata } from "next";
import { Onest } from "next/font/google";
import '@/styles/index.scss';
import { AuthProvider } from "@/contexts/AuthContext";
import Nav from "@/components/Nav/Nav";

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // adjust weights you actually use
  display: "swap",
});

export const metadata: Metadata = {
  title: "Routique — Your favourite look is waiting.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={onest.variable}>
      <body>
        <AuthProvider>
          <Nav />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
